syntax = "proto3";

package messages_service.messages.v1;
option go_package = "messages_service/messages/v1;messagesv1";

import "messages_service/messages/v1/models.proto";

service MessagesService {
  rpc SendMessage(SendMessageRequest) returns (SendMessageResponse);
  
  rpc GetChatHistory(GetChatHistoryRequest) returns (GetChatHistoryResponse);

  rpc GetLastMessages(GetLastMessagesRequest) returns (GetLastMessagesResponse);
  
  rpc GetUnreadCount(GetUnreadCountRequest) returns (GetUnreadCountResponse);

  rpc GetUnreadCounts(GetUnreadCountsRequest) returns (GetUnreadCountsResponse);

  rpc EditMessage(EditMessageRequest) returns (EditMessageResponse);

  rpc DeleteMessage(DeleteMessageRequest) returns (DeleteMessageResponse);

}

message SendMessageRequest {
  string chat_id = 1;
  Content content = 2;
  optional int64 reply_to_id = 3;
  string sender_id = 4;
}

message SendMessageResponse {
  Message message = 1;
}

message GetChatHistoryRequest {
  string chat_id = 1;
  int32 limit = 2;
  optional int64 before_message_id = 3;
}

message GetChatHistoryResponse {
  repeated Message messages = 1;
}

message GetLastMessagesRequest {
  repeated string chat_ids = 1;
}

message LastMessage {
  string chat_id = 1;
  Message message = 2;
}

message GetLastMessagesResponse {
  repeated LastMessage last_messages = 1;
}

message GetUnreadCountRequest {
  string chat_id = 1;
  int64 last_read_message_id = 2;
}

message GetUnreadCountResponse {
  int32 unread_count = 1;
}

message UnreadCountRequestItem {
  string chat_id = 1;
  int64 last_read_message_id = 2;
}

message GetUnreadCountsRequest {
  repeated UnreadCountRequestItem items = 1;
}

message UnreadCount {
  string chat_id = 1;
  int32 unread_count = 2;
}

message GetUnreadCountsResponse {
  repeated UnreadCount unread_counts = 1;
}

message EditMessageRequest {
  int64 message_id = 1;
  string sender_id = 2; 
  Content content = 3;
}

message EditMessageResponse {
  Message message = 1;
}

message DeleteMessageRequest {
  int64 message_id = 1;
  string user_id = 2;
}

message DeleteMessageResponse {}
