syntax = "proto3";

package users_service.users.v1;

option go_package = "users_service/users/v1;usersv1";

import "users_service/users/v1/models.proto";

service UsersService {
  rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);

  rpc GetUserByID(GetUserByIDRequest) returns (GetUserByIDResponse);

  rpc GetUsersByIDs(GetUsersByIDsRequest) returns (GetUsersByIDsResponse);

  rpc SearchUsers(SearchUsersRequest) returns (SearchUsersResponse);

  rpc GetOrCreateUserByLogin(GetOrCreateUserByLoginRequest) returns (GetOrCreateUserByLoginResponse);
}

service AuthService {
  rpc Login(LoginRequest) returns (LoginResponse);

  rpc ValidateToken(ValidateTokenRequest) returns (ValidateTokenResponse);
}

message CreateUserRequest {
  string username = 1;
  string login = 2;
  string email = 3;
  optional string avatar_url = 4;
}

message CreateUserResponse {
  User user = 1;
}

message GetUserByIDRequest {
  string user_id = 1; 
}

message GetUserByIDResponse {
  User user = 1;
}

message GetUsersByIDsRequest {
  repeated string user_ids = 1;
}

message GetUsersByIDsResponse {
  repeated User users = 1;
}

message SearchUsersRequest {
  string query = 1;
  repeated string user_ids = 2;
  string login = 3;
  int32 offset = 4;
  int32 limit = 5;
}

message SearchUsersResponse {
  repeated User users = 1;
  int32 count = 2;
}

message GetOrCreateUserByLoginRequest {
  string login = 1;
  string username = 2;
  string email = 3;
  optional string avatar_url = 4;
}

message GetOrCreateUserByLoginResponse {
  User user = 1;
  bool created = 2;
}

message LoginRequest {
  string username = 1;
  string password = 2;
}

message LoginResponse {
  User user = 1;
  string token = 2;
}

message ValidateTokenRequest {
  string token = 1;
}

message ValidateTokenResponse {
  User user = 1;
}
