syntax = "proto3";

package chats_service.chats.v1;

option go_package = "chats_service/chats/v1;chatsv1";

import "google/protobuf/timestamp.proto";

// Тип чата
enum ChatType {
  CHAT_TYPE_UNSPECIFIED = 0;
  // Чат между двумя пользователями
  CHAT_TYPE_PRIVATE = 1;
  // Групповой чат
  CHAT_TYPE_GROUP = 2;
}

// Роль пользователя
enum MemberRole {
  MEMBER_ROLE_UNSPECIFIED = 0;
  // Создатель чата
  MEMBER_ROLE_OWNER = 1;
  // Администратор
  MEMBER_ROLE_ADMIN = 2;
  // Обычный участник чата
  MEMBER_ROLE_MEMBER = 3;
}

// Чат
message Chat {
  string chat_id = 1;
  ChatType type = 2;
  optional string title = 3;
  string owner_id = 4;
  string last_message_preview = 5;
  google.protobuf.Timestamp created_at = 6;
  int64 last_message_id = 7;
  google.protobuf.Timestamp last_message_at = 8;
  google.protobuf.Timestamp updated_at = 9;
}

message ChatMember {
  string chat_id = 1;
  string user_id = 2;
  MemberRole role = 3;
  google.protobuf.Timestamp joined_at = 4;
  int64 last_read_message_id = 5;
}
